#version 460
#extension GL_EXT_shader_explicit_arithmetic_types_float32 : enable
 
layout(push_constant) uniform pushBlock {
         uint total;
};
layout(local_size_x=1024, local_size_y=1, local_size_z=1) in;
layout(binding=0) buffer buf_0 { float tensor_0[]; };

void main() {
        for (uint i = gl_GlobalInvocationID.x; i < total; i += gl_NumWorkGroups.x * gl_WorkGroupSize.x){
                {}[i] = float(1.000000);
        }
}